(function(){
  "use strict";
  // every15min 已上架。不带 /us/ 前缀，访客会自动落到自己所在地区的商店。
  var EVERY15MIN_APPSTORE="https://apps.apple.com/app/id6801988119";
  var residents={
    lyrebird:{name:"琴鸟 · 迎宾员",token:"♪",color:"#26c56a",pos:[49,19],lines:["欢迎回来～这座岛会记得你认识过谁。","我听过什么就能唱什么，还会给每段旋律配一支舞。Token 和 Dance，就是这么来的。","如果第一次来，先去记录花园或守护诊所吧。它们已经开放了。"],actions:[{label:"替我选下一站",action:"random"},{label:"看看岛屿护照",action:"passport"}]},
    bee:{name:"蜜蜂 · every15min",token:"15",color:"#2f75ff",pos:[20,47],lines:["嗡——欢迎来到记录花园。这里不要求你坚持写日记。","想起来时敲一行，就够了。一天会慢慢攒成许多个十五分钟的小格子。","所有记录都留在你自己的设备里。现在 App Store 上就能把我带回家啦。"],actions:[{label:"去 App Store 下载",href:EVERY15MIN_APPSTORE},{label:"看看官网",href:"https://every15min.tokendance.life/"},{label:"拜访下一位",action:"random"}]},
    goldie:{name:"Goldie · 守护伙伴",token:"●",color:"#ff63ae",pos:[78,45],lines:["汪！我负责记住重要的事：用药、发作、安全天数和复诊。","现实中的辅助犬也会陪伴癫痫朋友。我不替医生做决定，只把每天照顾好。","资料不离开手机，也没有账号、广告和追踪。"],actions:[{label:"去守守 Goldie",href:"https://goldie.tokendance.life/"},{label:"看看护照",action:"passport"}]},
    frog:{name:"青蛙 · 清净池塘",token:"↯",color:"#8e62e8",pos:[69,75],lines:["嘘——我在等下一只烦人的“飞虫”。","广告、弹窗和追踪器一冒头，我就用舌头把它拦下来。","手机广告拦截助手还在池塘边搭屋子。先盖一枚印章，等它开放。"],actions:[{label:"知道了，继续逛",action:"random"},{label:"看看护照",action:"passport"}]},
    otter:{name:"水獭 · Code Buddy",token:"{ }",color:"#ff9f1c",pos:[34,77],lines:["这颗蓝色代码石是我最顺手的工具。要用的时候，我一直都在菜单栏。","我不会抢走你的工作，只负责把零碎的代码小事递到手边。","macOS Code Buddy 的工坊正在施工。别担心，我把工具都收好了。"],actions:[{label:"继续探索",action:"random"},{label:"给园长写信",href:"mailto:tonybingpoon@gmail.com"}]}
  };
  var keys=Object.keys(residents),stamps=load("tokendance-stamps",[]),current="lyrebird",lineIndex=0,typingTimer=null,tourTimer=null,soundOn=false,audio=null,musicMaster=null,musicTimer=null,musicStep=0;
  var $=function(s){return document.querySelector(s)},$$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))};
  var arrival=$("#arrival"),world=$(".world"),visitor=$("#visitor"),dialogueText=$("#dialogue-text"),dialogueName=$("#dialogue-name"),speakerToken=$("#speaker-token"),actions=$("#dialogue-actions"),next=$("#dialogue-next"),passport=$("#passport"),scrim=$("#scrim"),toast=$("#toast");
  function load(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch(e){return fallback}}
  function save(){try{localStorage.setItem("tokendance-stamps",JSON.stringify(stamps))}catch(e){}}
  function ensureAudio(){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==="suspended")audio.resume();return audio}catch(e){return null}}
  function tone(freq,duration){if(!soundOn)return;var ctx=ensureAudio();if(!ctx)return;var o=ctx.createOscillator(),g=ctx.createGain();o.type="sine";o.frequency.value=freq;g.gain.setValueAtTime(.035,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+duration)}
  function musicNote(freq,start,duration,volume,type){if(!audio||!musicMaster)return;var o=audio.createOscillator(),g=audio.createGain();o.type=type||"sine";o.frequency.setValueAtTime(freq,start);g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(volume,start+.08);g.gain.exponentialRampToValueAtTime(.0001,start+duration);o.connect(g).connect(musicMaster);o.start(start);o.stop(start+duration+.05)}
  function scheduleMusicBar(){if(!soundOn||!musicMaster)return;var chords=[[261.63,329.63,392],[220,261.63,329.63],[174.61,220,261.63],[196,246.94,293.66]],melodies=[[523.25,659.25,783.99,659.25,587.33,523.25,493.88,392],[440,523.25,659.25,523.25,493.88,440,392,329.63],[349.23,440,523.25,440,392,349.23,329.63,261.63],[392,493.88,587.33,493.88,440,392,329.63,293.66]],ctx=audio,start=ctx.currentTime+.08,chord=chords[musicStep%4],melody=melodies[musicStep%4];chord.forEach(function(n){musicNote(n,start,4.65,.045,"sine")});melody.forEach(function(n,i){musicNote(n,start+i*.58,.48,i%3===0?.07:.045,"triangle")});musicNote(chord[0]*2,start+3.48,1.05,.035,"sine");musicStep++}
  function startMusic(){var ctx=ensureAudio();if(!ctx)return;stopMusic();musicMaster=ctx.createGain();musicMaster.gain.setValueAtTime(.22,ctx.currentTime);musicMaster.connect(ctx.destination);scheduleMusicBar();musicTimer=setInterval(scheduleMusicBar,4640)}
  function stopMusic(){if(musicTimer){clearInterval(musicTimer);musicTimer=null}if(musicMaster&&audio){var old=musicMaster;old.gain.cancelScheduledValues(audio.currentTime);old.gain.setValueAtTime(Math.max(old.gain.value,.0001),audio.currentTime);old.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.45);setTimeout(function(){try{old.disconnect()}catch(e){}},550);musicMaster=null}}
  function showToast(message){toast.textContent=message;toast.classList.add("show");clearTimeout(showToast.t);showToast.t=setTimeout(function(){toast.classList.remove("show")},1900)}
  function type(text){clearInterval(typingTimer);dialogueText.textContent="";var i=0;typingTimer=setInterval(function(){dialogueText.textContent=text.slice(0,++i);if(i>=text.length)clearInterval(typingTimer)},20)}
  function renderActions(items){actions.innerHTML="";items.forEach(function(item){var el=document.createElement(item.href?"a":"button");el.textContent=item.label;if(item.href){el.href=item.href;el.target=item.href.indexOf("http")===0?"_blank":null;el.rel="noopener"}else{el.type="button";el.dataset.action=item.action}actions.appendChild(el)})}
  function collect(id){if(stamps.indexOf(id)<0){stamps.push(id);save();tone(720,.18);showToast("获得一枚「"+residents[id].name.split(" · ")[0]+"」印章 ✦");updatePassport();if(stamps.length===keys.length)setTimeout(celebrate,500)}}
  function visit(id,scroll){var r=residents[id];if(!r)return;current=id;lineIndex=0;collect(id);$$('.resident-spot').forEach(function(x){x.classList.toggle("is-active",x.dataset.resident===id)});visitor.style.left=r.pos[0]+"%";visitor.style.top=r.pos[1]+"%";dialogueName.textContent=r.name;speakerToken.textContent=r.token;speakerToken.style.background=r.color;$(".name-tag").style.background=r.color;type(r.lines[0]);renderActions([]);next.hidden=r.lines.length<2;tone(420,.12);if(scroll!==false)$("#dialogue-zone").scrollIntoView({behavior:"smooth",block:"end"})}
  function advance(){var r=residents[current];lineIndex++;if(lineIndex<r.lines.length){type(r.lines[lineIndex]);tone(500+lineIndex*70,.08)}if(lineIndex>=r.lines.length-1){next.hidden=true;renderActions(r.actions)}}
  function randomResident(){var options=keys.filter(function(k){return k!==current}),id=options[Math.floor(Math.random()*options.length)];visit(id,false);$("#island").scrollIntoView({behavior:"smooth"})}
  function openPassport(){passport.classList.add("is-open");passport.setAttribute("aria-hidden","false");scrim.classList.add("is-open");$("#passport-button").setAttribute("aria-expanded","true");setTimeout(function(){$("#passport-close").focus()},300)}
  function closePassport(){passport.classList.remove("is-open");passport.setAttribute("aria-hidden","true");scrim.classList.remove("is-open");$("#passport-button").setAttribute("aria-expanded","false")}
  function updatePassport(){$$(".stamp").forEach(function(s){s.classList.toggle("is-collected",stamps.indexOf(s.dataset.stamp)>=0)});$("#stamp-count").textContent=stamps.length+"/5";$("#passport-progress").style.width=(stamps.length/5*100)+"%";$("#passport-message").textContent=stamps.length===5?"全员见面完成！这座岛现在认识你了。":"还有 "+(5-stamps.length)+" 位居民等着认识你。"}
  function celebrate(){showToast("护照完成！欢迎成为荣誉岛民 🎉");document.body.classList.add("celebrate");for(var i=0;i<18;i++){var c=document.createElement("i");c.className="confetti";c.style.left=Math.random()*100+"%";c.style.background=["#ffd91a","#ff4b3e","#2f75ff","#26c56a","#ff63ae"][i%5];c.style.animationDelay=Math.random()*.5+"s";document.body.appendChild(c);setTimeout(function(n){return function(){n.remove()}}(c),2400)}}
  function startTour(){clearInterval(tourTimer);var i=0;visit(keys[i],false);tourTimer=setInterval(function(){i++;if(i>=keys.length){clearInterval(tourTimer);showToast("导览结束，接下来随便逛逛吧");return}visit(keys[i],false)},4300);showToast("琴鸟开始带路啦")}
  function setSky(){var h=new Date().getHours(),sky=h>=19||h<6?"night":h>=17?"dusk":"day";world.dataset.sky=sky;document.body.dataset.sky=sky;$("#weather").textContent=sky==="night"?"☾ 星光":sky==="dusk"?"◒ 晚霞":"☀ 晴朗"}
  function tick(){var d=new Date(),days=["日","一","二","三","四","五","六"],m=String(d.getMinutes()).padStart(2,"0");$("#clock").textContent=(d.getMonth()+1)+"月"+d.getDate()+"日 · 周"+days[d.getDay()]+" · "+d.getHours()+":"+m}
  function enter(){arrival.classList.add("is-gone");document.body.classList.add("entered");try{localStorage.setItem("tokendance-visited","1")}catch(e){}tone(620,.22);setTimeout(function(){$("[data-resident='lyrebird']").focus()},650)}
  $$("[data-resident]").forEach(function(el){el.addEventListener("click",function(){clearInterval(tourTimer);visit(el.dataset.resident,true)})});
  $$('[data-focus]').forEach(function(el){el.addEventListener("click",function(){visit(el.dataset.focus,false);$("#island").scrollIntoView({behavior:"smooth"})})});
  next.addEventListener("click",advance);actions.addEventListener("click",function(e){var a=e.target.closest("[data-action]");if(!a)return;if(a.dataset.action==="random")randomResident();if(a.dataset.action==="passport")openPassport()});
  $("#passport-button").addEventListener("click",openPassport);$("#passport-close").addEventListener("click",closePassport);scrim.addEventListener("click",closePassport);$("#tour-button").addEventListener("click",startTour);$("#enter-island").addEventListener("click",enter);$("#return-visitor").addEventListener("click",enter);
  $("#sound-button").addEventListener("click",function(){soundOn=!soundOn;this.setAttribute("aria-pressed",String(soundOn));this.textContent=soundOn?"♫":"♩";this.setAttribute("aria-label",soundOn?"暂停岛屿音乐":"播放岛屿音乐");this.title=soundOn?"暂停岛屿音乐":"岛屿音乐";if(soundOn){startMusic();tone(659.25,.2);showToast("岛屿音乐已开启 ♫")}else{stopMusic();showToast("岛屿音乐已暂停")}});
  $("#shell-secret").addEventListener("click",function(){this.textContent="✦";this.disabled=true;showToast("捡到一枚会发光的贝壳。岛民说这是好兆头。");tone(880,.3)});
  $("#reset-progress").addEventListener("click",function(){stamps=[];save();updatePassport();showToast("护照已经翻到新的一页")});
  var notes=["今天适合记录一个被忽略的小瞬间。","小需求并不比大愿景低一等。","安静的软件，也可以很有力量。","先照顾好今天，再考虑很远的以后。","一个人做应用，也能养出一座岛。"];
  $("#new-note").addEventListener("click",function(){var n=notes[Math.floor(Math.random()*notes.length)];$("#daily-note").textContent=n;tone(680,.1)});
  document.addEventListener("keydown",function(e){if(e.key==="Escape")closePassport();if(/^[1-5]$/.test(e.key)){visit(keys[Number(e.key)-1],false)}});
  document.addEventListener("visibilitychange",function(){if(!soundOn)return;if(document.hidden)stopMusic();else startMusic()});
  if(matchMedia("(pointer:fine)").matches&&!matchMedia("(prefers-reduced-motion:reduce)").matches){world.addEventListener("pointermove",function(e){var x=(e.clientX/innerWidth-.5)*10,y=(e.clientY/innerHeight-.5)*7;$("#island-map").style.marginLeft=x+"px";$("#island-map").style.marginTop=y+"px"})}
  try{if(localStorage.getItem("tokendance-visited")){$("#return-visitor").hidden=false;$("#saved-stamps").textContent=stamps.length}}catch(e){}
  updatePassport();setSky();tick();setInterval(tick,30000);
})();
